### ISSUE TITLE
image should be updated

### ISSUE THREAD

**Issue by polarstern** [QuantLet/QID-1234-MVAsirdata#1]
![mvasirdata_1-1](https://cloud.githubusercontent.com/assets/14127572/10192136/5f9cad4c-677a-11e5-9055-c66e8a6bd773.png)
![mvasirdata_2-1](https://cloud.githubusercontent.com/assets/14127572/10192137/6271bfa8-677a-11e5-8a33-4532877719e2.png)
![mvasirdata_3-1](https://cloud.githubusercontent.com/assets/14127572/10192139/66251460-677a-11e5-91b3-8384bb29a5a1.png)

**Comment by quantomas** [comment]
nice pictures ;-)

**Comment by Tdannen** [comment]
haha...beware that quantomas is watching....always :)))
